In [1]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
from abc import ABC, abstractmethod

In [2]:
random_seed, np_random_seed = random.seed(505), np.random.seed(505)

In [3]:
pd.options.mode.chained_assignment = None  # default='warn'

In [4]:
from modules.classes import Document, Provider, Consumer, Recommender
from modules.samplers import provider_sampler, consumer_sampler
from modules.genre_preferences import generate_genre_preferences

In [5]:
# Movie Lens
ratings_df = pd.read_csv("ml-latest-small/ratings.csv")
movies_df = pd.read_csv("ml-latest-small/movies.csv")
movies_with_ratings_df = ratings_df.merge(movies_df, on="movieId", how="left")
documents_df = (
    movies_with_ratings_df[["movieId", "rating", "genres"]]
    .groupby(["movieId", "genres"])
    .mean()
    .reset_index()
)

In [6]:
movies_with_ratings_df.head()

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [7]:
documents_df["rating"] = documents_df["rating"].apply(lambda x: x / 5)

In [8]:
user_genre_preference = generate_genre_preferences(movies_with_ratings_df)

In [9]:
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [10]:
sampled_users = user_genre_preference.sample(600)
# Shuffle the sampled users to randomize the order
sampled_users = sampled_users.sample(frac=1).reset_index(drop=True)

In [11]:
### Users that are interested in niche movies
ten_percent = int(len(sampled_users) * 0.1)
users_niche_movies = sampled_users[:ten_percent]
users_general_interest = sampled_users[ten_percent:]

In [12]:
# Selecting the Niche Genre
niche_genre = "Western"

other_genres = list(users_niche_movies.columns)
other_genres.remove(niche_genre)

### update the genre preferences for niche movies fans
users_niche_movies[niche_genre] = np.where(
    users_niche_movies[niche_genre] > 0, users_niche_movies[niche_genre] * 4, 0.2
)
users_niche_movies[other_genres] /= 4

### update the genre preferences for the general movie fans
users_general_interest[niche_genre] /= 4

In [13]:
users_niche_movies.columns

Index(['Action', 'Adventure', 'Animation', 'Children', 'Comedy', 'Crime',
       'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'IMAX',
       'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War',
       'Western'],
      dtype='object')

In [14]:
niche_consumers_list = consumer_sampler(
    category_preferences_df=users_niche_movies, favorite_categories=set([niche_genre])
)
general_consumers_list = consumer_sampler(
    category_preferences_df=users_general_interest
)
consumers_list = (
    niche_consumers_list + general_consumers_list
)  # try it once with niche and another with general
random.shuffle(consumers_list)

In [15]:
len(consumers_list)

600

In [16]:
niche_consumers_set = set([consumer.consumer_id for consumer in niche_consumers_list])
general_consumers_set = set(
    [consumer.consumer_id for consumer in general_consumers_list]
)

In [17]:
# Niche Documents
niche_documents = documents_df[documents_df["genres"].str.contains(niche_genre)]

### SVD Recommender

In [18]:
from surprise import Dataset, Reader, SVD
from surprise.model_selection import train_test_split

class MatrixFactorizationRecommender(Recommender):
    def __init__(
        self,
        recommender_id,
        fee_per_click=0,
        fee_per_show=0,
        base_fee=0,
        exploration_prob=0.2,
        specialized_categories=set(),
        prohibited_categories=set(),
        weighted_category={},
        weighted_value=0.5,
    ):
        """
        Initialize the PopularRecommender.

        Args:
            exploration_prob (float): Probability of exploring (randomly selecting documents).
        """
        super().__init__()
        self.recommender_id = recommender_id
        self.exploration_prob = exploration_prob
        self.recommendations = {}
        self.historical_recommendations = []
        self.fee_per_click = fee_per_click
        self.fee_per_show = fee_per_show
        self.base_fee = base_fee
        self.profit = []
        self.specialized_categories = specialized_categories
        self.prohibited_categories = prohibited_categories
        # weighted category variables
        self.weighted_category = (
            weighted_category  # dictionary of category as key and weight as value
        )
        self.weighted_value = weighted_value
        # self.exploration_prob = exploration_prob
        self.algo = SVD()
        self.has_trained_model = False  # Track if the model has been trained yet
        self.precomputed_recommendations = (
            {}
        )  # Dictionary to store precomputed recommendations

    def train_model_if_ready(self):
        """Train the SVD model once there are enough interactions and precompute recommendations."""
        if len(self.interactions) > 10:  # Arbitrary threshold, adjust as needed
            print("Training model")
            reader = Reader(rating_scale=(0, 1))
            data = Dataset.load_from_df(
                pd.DataFrame(
                    self.interactions, columns=["consumer_id", "doc_id", "rating"]
                ),
                reader,
            )
            trainset = data.build_full_trainset()
            self.algo.fit(trainset)
            self.has_trained_model = True
            print("Model training completed")

            # Precompute recommendations for all users
            self.precompute_recommendations()

    def precompute_recommendations(self):
        """Precompute recommendations for all users and store them in a dictionary."""
        print("Precomputing recommendations for all users")
        # Get all unique users and items
        user_ids = {interaction[0] for interaction in self.interactions}
        item_ids = {doc.doc_id for doc in self.documents}

        # Precompute predictions for each user
        for user_id in user_ids:
            predictions = [
                (item_id, self.algo.predict(user_id, item_id).est)
                for item_id in item_ids
            ]
            # Sort items by predicted rating and store the top N items
            sorted_items = sorted(predictions, key=lambda x: x[1], reverse=True)
            self.precomputed_recommendations[user_id] = [
                item_id for item_id, _ in sorted_items
            ]
        print("Precomputation completed")

    def recommend_documents(self, consumers, slate_size=5):
        recommendations = {}

        if not self.has_trained_model:
            self.update_documents_list()  # Collect documents from providers

        for consumer in consumers:
            consumer_id = consumer.consumer_id
            recommended_documents = []

            # Get the list of items already clicked by the consumer
            clicked_items = self.consumer_docs_ids_clicked.get(consumer_id, set())

            # Check if we should explore (cold start) or use precomputed recommendations
            if not self.has_trained_model:
                # Cold start: Recommend random documents excluding already clicked items
                available_documents = [
                    doc for doc in self.documents if doc.doc_id not in clicked_items
                ]
                recommended_documents = random.sample(available_documents, min(slate_size, len(available_documents)))
            else:
                # Retrieve precomputed recommendations, excluding already clicked items
                top_item_ids = [
                    item_id
                    for item_id in self.precomputed_recommendations.get(consumer_id, [])
                    if item_id not in clicked_items
                ][:slate_size]
                recommended_documents = [doc for doc in self.documents if doc.doc_id in top_item_ids]

            # Store recommendations and record shows for tracking purposes
            recommendations[consumer_id] = recommended_documents
            for document in recommended_documents:
                self.record_show(document.provider_id)

        return recommendations

### Single Recommender System

In [19]:
def run_competing_rec_experiment_df_export(
    consumers, providers, recommenders, num_days=5, slate_size=3, num_cycles=1
):
    """
    Run a multi-recommender experiment.

    Args:
        consumers (list): List of Consumer instances.
        providers (list): List of Provider instances.
        recommenders (dict): Dictionary of Recommender instances where keys are recommender IDs.
        num_days (int, optional): Number of days to run the experiment (default is 5).
        slate_size (int, optional): Number of documents to recommend to each consumer (default is 3).

    Returns:
        pd.DataFrame: DataFrame containing provider data.
        pd.DataFrame: DataFrame containing consumer data.
        pd.DataFrame: DataFrame containing recommender system data.
    """
    provider_data = []
    consumer_data = []
    recommender_data = []
    customers_recommender_choice = []

    recommender_values = list(recommenders.values())
    general_recommender = recommender_values[0]

    # Subscribe consumers to the recommender
    for consumer in consumers:
        general_recommender.connect_consumer(consumer)
        consumer.subscribe_to_recommender_system(general_recommender.recommender_id)

    print("General Recommender", general_recommender.connected_consumers.keys())

    # Subscribe providers to both recommenders
    for provider in providers:
        general_recommender.connect_provider(provider)
        provider.subscribe_to_recommender_system(general_recommender.recommender_id)

    ### LOGGING ###
    print(
        "Connected to General recommender:",
        len(general_recommender.connected_consumers),
    )

    # Run the experiment for the specified number of days
    for cycle in range(1, num_cycles + 1):
        for day in range(1, num_days + 1):
            print("===============> Day:", day, "<===============")
            # Organize consumers into lists based on the recommender they chose
            consumers_by_recommender = {
                recommender_id: [] for recommender_id in recommenders.keys()
            }
            for (
                consumer
            ) in consumers:  # Iterate over the consumers for the current recommender ID
                chosen_recommender_id = consumer.choose_recommender()
                if chosen_recommender_id is None:
                    continue
                # Append recommender to consumer to evaluate UCB
                customers_recommender_choice.append(
                    [consumer.consumer_id, chosen_recommender_id]
                )  # used for analysis
                consumers_by_recommender[chosen_recommender_id].append(consumer)

            # Make recommendations for each recommender's associated consumers
            recommendations = {}
            for (
                recommender_id,
                recommender_consumers,
            ) in consumers_by_recommender.items():
                recommender = recommenders[recommender_id]
                slate_documents = recommender.recommend_documents(
                    recommender_consumers, slate_size=slate_size
                )
                for consumer in recommender_consumers:
                    recommendations[consumer.consumer_id] = (
                        recommender_id,
                        slate_documents[consumer.consumer_id],
                    )

            # Simulate user response, update satisfaction scores, and record clicks
            clicked_documents = {
                consumer.consumer_id: [] for consumer in consumers
            }  # Initialize with empty lists
            for consumer in consumers:
                # continue if the consumer is not connected to any recommenders
                if len(consumer.available_recommenders) == 0:
                    print("Consumer is not connected to any recommenders")
                    continue

                consumer_id = consumer.consumer_id
                recommender_id, recommended_documents = recommendations[consumer_id]
                slate_documents = recommended_documents
                chosen_recommender_id = (
                    recommender_id  # Choose recommender for the current user
                )
                responses = consumer.simulate_response(
                    slate_documents, recommender_system_id=chosen_recommender_id
                )

                # Collect clicked items
                for i, response in enumerate(responses):
                    # record interaction (consumer_id, doc_id, rating)
                    recommenders[chosen_recommender_id].add_interaction(
                        consumer_id, slate_documents[i], response["click"]
                    )
                    if response.get("click", 0) == 1:
                        clicked_documents[consumer_id].append(slate_documents[i])
                        recommenders[chosen_recommender_id].record_click(
                            consumer_id, slate_documents[i]
                        )

        # Charge subscription fees to providers
        for recommender in recommenders.values():
            recommender.charge_subscription_fees()

        # Get profit for each provider
        for provider in providers:
            for recommender_id, recommender in recommenders.items():
                if recommender_id in provider.connected_recommenders.keys():
                    provider_data.append(
                        [
                            provider.provider_id,
                            recommender_id,
                            (
                                provider.profit.get(recommender_id, [0])[cycle - 1]
                                if cycle
                                <= len(provider.profit.get(recommender_id, [0]))
                                else 0
                            ),
                            cycle,
                            (
                                provider.pay_cycle_fee.get(recommender_id, [0])[
                                    cycle - 1
                                ]
                                if cycle
                                <= len(provider.pay_cycle_fee.get(recommender_id, [0]))
                                else 0
                            ),
                            (
                                provider.pay_cycle_clicks.get(recommender_id, [0])[
                                    cycle - 1
                                ]
                                if cycle
                                <= len(
                                    provider.pay_cycle_clicks.get(recommender_id, [0])
                                )
                                else 0
                            ),
                            (
                                provider.pay_cycle_shows.get(recommender_id, [0])[
                                    cycle - 1
                                ]
                                if cycle
                                <= len(
                                    provider.pay_cycle_shows.get(recommender_id, [0])
                                )
                                else 0
                            ),
                            len(
                                [
                                    rec
                                    for rec in provider.connected_recommenders.keys()
                                    if provider.connected_recommenders[rec] == 1
                                ]
                            ),
                            (
                                "niche"
                                if provider.provider_id in niche_providers_set
                                else "general"
                            ),
                        ]
                    )
        for consumer in consumers:
            for recommender_id, recommender in recommenders.items():
                if recommender_id in consumer.connected_recommenders.keys():
                    consumer_id = consumer.consumer_id
                    consumer_satisfaction_score = consumer.get_satisfaction_score(
                        recommender_system_id=recommender_id
                    )
                    rec_state = (
                        "connected"
                        if consumer.connected_recommenders[recommender_id] == 1
                        else ""
                    )
                    controlled = (
                        "niche"
                        if consumer.consumer_id in niche_consumers_set
                        else "general"
                    )
                    consumer_data.append(
                        [
                            consumer_id,
                            recommender_id,
                            cycle,
                            consumer_satisfaction_score,
                            rec_state,
                            controlled,
                        ]
                    )

        # Update the subscription for each provider
        for provider in providers:
            unsubscribed_list = provider.update_recommender_subscription()
            for recommender_id, recommender in recommenders.items():
                if recommender_id in unsubscribed_list:
                    recommender.disconnect_provider(provider.provider_id)

        for recommender_id, recommender in recommenders.items():
            num_connected_providers = len(recommender.connected_providers)
            num_connected_consumers = len(recommender.connected_consumers)
            total_profit = recommender.profit[-1]
            recommender_data.append(
                [
                    recommender_id,
                    num_connected_providers,
                    num_connected_consumers,
                    total_profit,
                    cycle,
                ]
            )

        print("\n====================================================")
        print("===============> Finished Cycle:", cycle, "<================")
        print("==================================================== \n")

    # Convert lists to DataFrames
    provider_df = pd.DataFrame(
        provider_data,
        columns=[
            "provider_id",
            "recommender_id",
            "profit",
            "cycle",
            "fee",
            "clicks",
            "shows",
            "connected_recommenders",
            "controlled",
        ],
    )
    consumer_df = pd.DataFrame(
        consumer_data,
        columns=[
            "consumer_id",
            "recommender_id",
            "cycle",
            "satisfaction_score",
            "rec_state",
            "controlled",
        ],
    )
    recommender_df = pd.DataFrame(
        recommender_data,
        columns=[
            "recommender_id",
            "num_connected_providers",
            "num_connected_consumers",
            "total_profit",
            "cycle",
        ],
    )
    customer_recommender_df = pd.DataFrame(
        customers_recommender_choice, columns=["customer_id", "recommender_id"]
    )

    return provider_df, consumer_df, recommender_df, customer_recommender_df

In [20]:
import pandas as pd
import numpy as np
from collections import Counter

# Define the sets of variables for different experiments
experiments = [
    {
        "name": "Experiment 1",
        "num_days": 30,
        "num_cycles": 60,
        "slate_size": 5,
        "num_recommenders": 1,
        "specialized_categories": [
            set(),
        ],
        "prohibited_categories": [
            set(),
        ],
        "weighted_category": [  # value between 0 and 1. default=0.5
            {},
        ],
    },
]

# List of random seeds
random_seeds = [random_seed]

# Initialize DataFrame to store category frequencies per experiment and recommender
category_freq_df = pd.DataFrame(
    columns=["experiment_name", "recommender_id", "category", "frequency"]
)

# Initialize lists to store results of all experiments
all_provider_data = []
all_consumer_data = []
all_recommender_data = []
all_customer_recommender_data = []

# Consumers
num_consumers = consumers_list

# Providers
doc_mean_std = (500, 100)
num_docs = 500
num_providers = 10

# Recommender system base fee
recs_fee = 0
decremental_fee_flag = False  # base_fee = recs_fee / number of recs

for seed in random_seeds:
    np.random.seed(seed)
    random.seed(seed)
    # Loop over each experiment configuration
    for i, exp in enumerate(experiments):
        # Initialize providers
        niche_providers_list = provider_sampler(
            niche_documents,
            int(num_providers * 0.1),
            len(niche_documents),
            starting_id=1,
        )  # 10% are niche providers
        niche_providers_set = set(
            [provider.provider_id for provider in niche_providers_list]
        )

        general_providers_list = provider_sampler(
            documents_df, int(num_providers * 0.9), num_docs, starting_id=2
        )  # 90% are general providers

        providers_list = niche_providers_list + general_providers_list
        random.shuffle(providers_list)

        print(
            f"Running experiment: {exp['name']} | seed: {seed} | number of recommenders: {exp['num_recommenders']}"
        )

        # Initialize recommenders for this experiment
        recommenders = {}
        for j in range(exp["num_recommenders"]):
            recommender_id = f"popular_{j+1}_exp_{i}_seed_{seed}"

            # decrease the fee based on the number of recommenders
            if decremental_fee_flag == True:
                base_fee = recs_fee / exp["num_recommenders"]
            else:
                base_fee = recs_fee

            recommenders[recommender_id] = MatrixFactorizationRecommender(
                recommender_id=recommender_id,
                fee_per_click=0.1,
                fee_per_show=0.01,
                base_fee=base_fee,
                prohibited_categories=exp["prohibited_categories"][
                    j
                ],  # gets the prohibited categories from "prohibited_categories":[[],[]]
                weighted_category=exp["weighted_category"][j],
                specialized_categories=exp["specialized_categories"][j],
            )

        # Run the experiment
        provider_df, consumer_df, recommender_df, customer_recommender_df = (
            run_competing_rec_experiment_df_export(
                consumers=consumers_list,
                providers=providers_list,
                recommenders=recommenders,
                num_days=exp["num_days"],
                slate_size=exp["slate_size"],
                num_cycles=exp["num_cycles"],
            )
        )

        # Calculate category frequencies
        for j in range(exp["num_recommenders"]):
            recommender_id = f"popular_{j+1}_exp_{i}_seed_{seed}"

            category_counter = Counter()
            for doc_list in recommenders[recommender_id].historical_recommendations:
                for doc in doc_list:
                    for category in doc.categories:
                        category_counter[category] += 1

            # Collect rows to be added to category_freq_df
            rows_to_append = []
            for category, frequency in category_counter.items():
                rows_to_append.append(
                    {
                        "experiment_name": exp["name"],
                        "recommender_id": recommender_id,
                        "category": category,
                        "frequency": frequency,
                    }
                )

            # Append rows to DataFrame using concat
            category_freq_df = pd.concat(
                [category_freq_df, pd.DataFrame(rows_to_append)], ignore_index=True
            )

        # Add experiment configuration to the dataframes
        provider_df["experiment_id"] = i
        provider_df["random_seed"] = seed
        consumer_df["experiment_id"] = i
        consumer_df["random_seed"] = seed
        recommender_df["experiment_id"] = i
        recommender_df["random_seed"] = seed
        customer_recommender_df["experiment_id"] = i
        customer_recommender_df["random_seed"] = seed

        # Append the results to the lists
        all_provider_data.append(provider_df)
        all_consumer_data.append(consumer_df)
        all_recommender_data.append(recommender_df)
        all_customer_recommender_data.append(customer_recommender_df)

# Concatenate all results into single dataframes
final_provider_df = pd.concat(all_provider_data, ignore_index=True)
final_consumer_df = pd.concat(all_consumer_data, ignore_index=True)
final_recommender_df = pd.concat(all_recommender_data, ignore_index=True)
final_customer_recommender_df = pd.concat(
    all_customer_recommender_data, ignore_index=True
)

# Save the dataframes to CSV files for analysis
save_dir = "surprise_data_export"
seed = "505"

final_provider_df.to_csv(f"surprise_data_export/provider_data_{seed}.csv", index=False)
final_consumer_df.to_csv(f"surprise_data_export/consumer_data_{seed}.csv", index=False)
final_recommender_df.to_csv(
    f"surprise_data_export/recommender_data_{seed}.csv", index=False
)
final_customer_recommender_df.to_csv(
    f"surprise_data_export/customer_recommender_data_{seed}.csv", index=False
)
category_freq_df.to_csv(
    f"surprise_data_export/category_frequencies_{seed}.csv", index=False
)

print("Experiment Complete!")

Running experiment: Experiment 1 | seed: None | number of recommenders: 1
General Recommender dict_keys([229, 109, 406, 450, 49, 17, 23, 383, 387, 228, 556, 265, 69, 354, 380, 397, 579, 451, 259, 470, 478, 11, 106, 213, 421, 334, 452, 585, 93, 575, 340, 216, 112, 417, 360, 215, 72, 78, 59, 214, 299, 364, 505, 318, 25, 105, 39, 179, 483, 209, 316, 362, 187, 14, 372, 487, 86, 464, 590, 418, 9, 554, 489, 248, 386, 427, 219, 425, 308, 584, 408, 254, 148, 488, 459, 284, 353, 42, 98, 68, 330, 591, 223, 513, 525, 162, 436, 405, 479, 180, 530, 480, 274, 355, 269, 90, 296, 352, 297, 40, 291, 484, 242, 127, 424, 24, 593, 91, 431, 392, 435, 77, 251, 197, 111, 599, 295, 264, 532, 324, 142, 3, 66, 27, 282, 518, 415, 311, 58, 373, 173, 403, 234, 38, 26, 398, 390, 7, 482, 453, 361, 578, 231, 139, 200, 163, 186, 508, 461, 34, 382, 570, 177, 305, 499, 6, 249, 19, 342, 288, 30, 194, 100, 241, 395, 543, 394, 266, 136, 586, 448, 207, 76, 544, 217, 301, 594, 519, 460, 492, 322, 137, 85, 122, 367, 449, 158, 558, 244, 344, 104, 568, 545, 485, 79, 366, 533, 551, 312, 81, 540, 384, 588, 474, 4, 349, 146, 48, 320, 150, 183, 202, 170, 420, 165, 151, 457, 410, 63, 126, 171, 168, 326, 196, 542, 476, 506, 310, 332, 210, 389, 129, 71, 138, 18, 22, 445, 152, 281, 113, 327, 566, 271, 429, 471, 134, 521, 257, 595, 576, 240, 261, 516, 335, 407, 587, 16, 331, 555, 339, 527, 468, 211, 434, 496, 447, 53, 245, 290, 195, 227, 260, 573, 400, 531, 65, 270, 232, 235, 333, 426, 224, 130, 371, 184, 279, 523, 94, 348, 370, 369, 498, 541, 149, 439, 329, 356, 140, 589, 102, 108, 135, 190, 547, 80, 535, 378, 1, 56, 475, 363, 444, 204, 141, 62, 552, 191, 176, 103, 89, 423, 379, 539, 465, 236, 365, 512, 315, 50, 55, 220, 302, 193, 188, 583, 167, 309, 493, 553, 99, 247, 2, 559, 514, 325, 154, 88, 504, 293, 472, 294, 502, 314, 43, 119, 110, 563, 409, 172, 47, 549, 33, 486, 157, 181, 454, 116, 222, 253, 238, 118, 45, 144, 166, 413, 132, 463, 31, 430, 351, 440, 128, 490, 411, 313, 368, 446, 537, 286, 433, 250, 221, 280, 199, 561, 87, 456, 35, 36, 307, 567, 131, 133, 262, 161, 443, 292, 57, 550, 357, 272, 164, 120, 469, 107, 230, 117, 338, 522, 275, 503, 46, 560, 572, 15, 64, 526, 12, 205, 156, 52, 208, 155, 74, 494, 393, 565, 377, 123, 437, 175, 359, 83, 51, 376, 37, 273, 206, 182, 145, 159, 201, 511, 598, 515, 82, 536, 404, 237, 422, 524, 13, 466, 239, 203, 276, 92, 29, 336, 125, 304, 317, 75, 507, 442, 501, 198, 350, 500, 95, 321, 60, 462, 491, 225, 557, 375, 32, 192, 571, 328, 97, 258, 243, 473, 528, 432, 455, 226, 41, 67, 278, 581, 388, 419, 477, 0, 169, 246, 396, 28, 268, 44, 114, 178, 401, 574, 212, 497, 582, 562, 509, 96, 283, 21, 577, 343, 185, 5, 569, 267, 121, 520, 510, 143, 233, 495, 256, 347, 399, 84, 458, 529, 115, 517, 402, 337, 70, 289, 345, 534, 10, 428, 323, 174, 160, 8, 285, 381, 412, 438, 385, 73, 189, 374, 252, 319, 298, 597, 391, 54, 277, 538, 441, 580, 218, 147, 596, 303, 20, 124, 255, 467, 564, 341, 101, 548, 414, 416, 61, 358, 592, 546, 300, 481, 346, 287, 306, 263, 153])
Connected to General recommender: 600
===============> Day: 1 <===============
===============> Day: 2 <===============
===============> Day: 3 <===============
===============> Day: 4 <===============
===============> Day: 5 <===============
===============> Day: 6 <===============
===============> Day: 7 <===============
===============> Day: 8 <===============
===============> Day: 9 <===============
===============> Day: 10 <===============
===============> Day: 11 <===============
===============> Day: 12 <===============
===============> Day: 13 <===============
===============> Day: 14 <===============
===============> Day: 15 <===============
===============> Day: 16 <===============
===============> Day: 17 <===============
===============> Day: 18 <===============
===============> Day: 19 <===============
===============> Day: 20 <===============
===============> Day: 21 <===============
===============> Day: 22 <===============
===============> Day: 23 <===============
===============> Day: 24 <===============
===============> Day: 25 <===============
===============> Day: 26 <===============
===============> Day: 27 <===============
===============> Day: 28 <===============
===============> Day: 29 <===============
===============> Day: 30 <===============
Training model
Model training completed
Precomputing recommendations for all users
Precomputation completed

====================================================
===============> Finished Cycle: 1 <================
====================================================

===============> Day: 1 <===============
===============> Day: 2 <===============
===============> Day: 3 <===============
===============> Day: 4 <===============
===============> Day: 5 <===============
===============> Day: 6 <===============
===============> Day: 7 <===============
===============> Day: 8 <===============
===============> Day: 9 <===============
===============> Day: 10 <===============
===============> Day: 11 <===============
===============> Day: 12 <===============
===============> Day: 13 <===============
===============> Day: 14 <===============
===============> Day: 15 <===============
===============> Day: 16 <===============
===============> Day: 17 <===============
===============> Day: 18 <===============
===============> Day: 19 <===============
===============> Day: 20 <===============
===============> Day: 21 <===============
===============> Day: 22 <===============
===============> Day: 23 <===============
===============> Day: 24 <===============
===============> Day: 25 <===============
===============> Day: 26 <===============
===============> Day: 27 <===============
===============> Day: 28 <===============
===============> Day: 29 <===============
===============> Day: 30 <===============
Training model
Model training completed
Precomputing recommendations for all users
Precomputation completed

====================================================
===============> Finished Cycle: 2 <================
====================================================

===============> Day: 1 <===============
===============> Day: 2 <===============
===============> Day: 3 <===============
===============> Day: 4 <===============
===============> Day: 5 <===============
===============> Day: 6 <===============
===============> Day: 7 <===============
===============> Day: 8 <===============
===============> Day: 9 <===============
===============> Day: 10 <===============
===============> Day: 11 <===============
===============> Day: 12 <===============
===============> Day: 13 <===============
===============> Day: 14 <===============
===============> Day: 15 <===============
===============> Day: 16 <===============
===============> Day: 17 <===============
===============> Day: 18 <===============
===============> Day: 19 <===============
===============> Day: 20 <===============
===============> Day: 21 <===============
===============> Day: 22 <===============
===============> Day: 23 <===============
===============> Day: 24 <===============
===============> Day: 25 <===============
===============> Day: 26 <===============
===============> Day: 27 <===============
===============> Day: 28 <===============
===============> Day: 29 <===============
===============> Day: 30 <===============
Training model
Model training completed
Precomputing recommendations for all users
Precomputation completed

====================================================
===============> Finished Cycle: 3 <================
====================================================

===============> Day: 1 <===============
===============> Day: 2 <===============
===============> Day: 3 <===============
===============> Day: 4 <===============
===============> Day: 5 <===============
===============> Day: 6 <===============
===============> Day: 7 <===============
===============> Day: 8 <===============
===============> Day: 9 <===============
===============> Day: 10 <===============
===============> Day: 11 <===============
===============> Day: 12 <===============
===============> Day: 13 <===============
===============> Day: 14 <===============
===============> Day: 15 <===============
===============> Day: 16 <===============
===============> Day: 17 <===============
===============> Day: 18 <===============
===============> Day: 19 <===============
===============> Day: 20 <===============
===============> Day: 21 <===============
===============> Day: 22 <===============
===============> Day: 23 <===============
===============> Day: 24 <===============
===============> Day: 25 <===============
===============> Day: 26 <===============
===============> Day: 27 <===============
===============> Day: 28 <===============
===============> Day: 29 <===============
===============> Day: 30 <===============
Training model
Model training completed
Precomputing recommendations for all users
Precomputation completed

====================================================
===============> Finished Cycle: 4 <================
====================================================

===============> Day: 1 <===============
===============> Day: 2 <===============
===============> Day: 3 <===============
===============> Day: 4 <===============
===============> Day: 5 <===============
===============> Day: 6 <===============
===============> Day: 7 <===============
===============> Day: 8 <===============
===============> Day: 9 <===============
===============> Day: 10 <===============
===============> Day: 11 <===============
===============> Day: 12 <===============
===============> Day: 13 <===============
===============> Day: 14 <===============
===============> Day: 15 <===============
===============> Day: 16 <===============
===============> Day: 17 <===============
===============> Day: 18 <===============
===============> Day: 19 <===============
===============> Day: 20 <===============
===============> Day: 21 <===============
===============> Day: 22 <===============
===============> Day: 23 <===============
===============> Day: 24 <===============
===============> Day: 25 <===============
===============> Day: 26 <===============
===============> Day: 27 <===============
===============> Day: 28 <===============
===============> Day: 29 <===============
===============> Day: 30 <===============
Training model
Model training completed
Precomputing recommendations for all users
Precomputation completed

====================================================
===============> Finished Cycle: 5 <================
====================================================

===============> Day: 1 <===============
===============> Day: 2 <===============
===============> Day: 3 <===============
===============> Day: 4 <===============
===============> Day: 5 <===============
===============> Day: 6 <===============
===============> Day: 7 <===============
===============> Day: 8 <===============
===============> Day: 9 <===============
===============> Day: 10 <===============
===============> Day: 11 <===============
===============> Day: 12 <===============
===============> Day: 13 <===============
===============> Day: 14 <===============
===============> Day: 15 <===============
===============> Day: 16 <===============
===============> Day: 17 <===============
===============> Day: 18 <===============
===============> Day: 19 <===============
===============> Day: 20 <===============
===============> Day: 21 <===============
===============> Day: 22 <===============
===============> Day: 23 <===============
===============> Day: 24 <===============
===============> Day: 25 <===============
===============> Day: 26 <===============
===============> Day: 27 <===============
===============> Day: 28 <===============
===============> Day: 29 <===============
===============> Day: 30 <===============
Training model
Model training completed
Precomputing recommendations for all users
Precomputation completed

====================================================
===============> Finished Cycle: 6 <================
====================================================

===============> Day: 1 <===============
===============> Day: 2 <===============
===============> Day: 3 <===============
===============> Day: 4 <===============
===============> Day: 5 <===============
===============> Day: 6 <===============
===============> Day: 7 <===============
===============> Day: 8 <===============
===============> Day: 9 <===============
===============> Day: 10 <===============
===============> Day: 11 <===============
===============> Day: 12 <===============
===============> Day: 13 <===============
===============> Day: 14 <===============
===============> Day: 15 <===============
===============> Day: 16 <===============
===============> Day: 17 <===============
===============> Day: 18 <===============
===============> Day: 19 <===============
===============> Day: 20 <===============
===============> Day: 21 <===============
===============> Day: 22 <===============
===============> Day: 23 <===============
===============> Day: 24 <===============
===============> Day: 25 <===============
===============> Day: 26 <===============
===============> Day: 27 <===============
===============> Day: 28 <===============
===============> Day: 29 <===============
===============> Day: 30 <===============
Training model
Model training completed
Precomputing recommendations for all users
Precomputation completed

====================================================
===============> Finished Cycle: 7 <================
====================================================

===============> Day: 1 <===============
===============> Day: 2 <===============
===============> Day: 3 <===============
===============> Day: 4 <===============
===============> Day: 5 <===============
===============> Day: 6 <===============
===============> Day: 7 <===============
===============> Day: 8 <===============
===============> Day: 9 <===============
===============> Day: 10 <===============
===============> Day: 11 <===============
===============> Day: 12 <===============
===============> Day: 13 <===============
===============> Day: 14 <===============
===============> Day: 15 <===============
===============> Day: 16 <===============
===============> Day: 17 <===============
===============> Day: 18 <===============
===============> Day: 19 <===============
===============> Day: 20 <===============
===============> Day: 21 <===============
===============> Day: 22 <===============
===============> Day: 23 <===============
===============> Day: 24 <===============
===============> Day: 25 <===============
===============> Day: 26 <===============
===============> Day: 27 <===============
===============> Day: 28 <===============
===============> Day: 29 <===============
===============> Day: 30 <===============
Training model
Model training completed
Precomputing recommendations for all users
Precomputation completed

====================================================
===============> Finished Cycle: 8 <================
====================================================

===============> Day: 1 <===============
===============> Day: 2 <===============
===============> Day: 3 <===============
===============> Day: 4 <===============
===============> Day: 5 <===============
===============> Day: 6 <===============
===============> Day: 7 <===============
===============> Day: 8 <===============
===============> Day: 9 <===============
===============> Day: 10 <===============
===============> Day: 11 <===============
===============> Day: 12 <===============
===============> Day: 13 <===============
===============> Day: 14 <===============
===============> Day: 15 <===============
===============> Day: 16 <===============
===============> Day: 17 <===============
===============> Day: 18 <===============
===============> Day: 19 <===============
===============> Day: 20 <===============
===============> Day: 21 <===============
===============> Day: 22 <===============
===============> Day: 23 <===============
===============> Day: 24 <===============
===============> Day: 25 <===============
===============> Day: 26 <===============
===============> Day: 27 <===============
===============> Day: 28 <===============
===============> Day: 29 <===============
===============> Day: 30 <===============
Training model
Model training completed
Precomputing recommendations for all users
Precomputation completed

====================================================
===============> Finished Cycle: 9 <================
====================================================

===============> Day: 1 <===============
===============> Day: 2 <===============
===============> Day: 3 <===============
===============> Day: 4 <===============
===============> Day: 5 <===============
===============> Day: 6 <===============
===============> Day: 7 <===============
===============> Day: 8 <===============
===============> Day: 9 <===============
===============> Day: 10 <===============
===============> Day: 11 <===============
===============> Day: 12 <===============
===============> Day: 13 <===============
===============> Day: 14 <===============
===============> Day: 15 <===============
===============> Day: 16 <===============
===============> Day: 17 <===============
===============> Day: 18 <===============
===============> Day: 19 <===============
===============> Day: 20 <===============
===============> Day: 21 <===============
===============> Day: 22 <===============
===============> Day: 23 <===============
===============> Day: 24 <===============
===============> Day: 25 <===============
===============> Day: 26 <===============
===============> Day: 27 <===============
===============> Day: 28 <===============
===============> Day: 29 <===============
===============> Day: 30 <===============
Training model
Model training completed
Precomputing recommendations for all users
Precomputation completed

====================================================
===============> Finished Cycle: 10 <================
====================================================

===============> Day: 1 <===============
===============> Day: 2 <===============
===============> Day: 3 <===============
===============> Day: 4 <===============
===============> Day: 5 <===============
===============> Day: 6 <===============
===============> Day: 7 <===============
===============> Day: 8 <===============
===============> Day: 9 <===============
===============> Day: 10 <===============
===============> Day: 11 <===============
===============> Day: 12 <===============
===============> Day: 13 <===============
===============> Day: 14 <===============
===============> Day: 15 <===============
===============> Day: 16 <===============
===============> Day: 17 <===============
===============> Day: 18 <===============
===============> Day: 19 <===============
===============> Day: 20 <===============
===============> Day: 21 <===============
===============> Day: 22 <===============
===============> Day: 23 <===============
===============> Day: 24 <===============
===============> Day: 25 <===============
===============> Day: 26 <===============
===============> Day: 27 <===============
===============> Day: 28 <===============
===============> Day: 29 <===============
===============> Day: 30 <===============
Training model
Model training completed
Precomputing recommendations for all users
Precomputation completed

====================================================
===============> Finished Cycle: 11 <================
====================================================

===============> Day: 1 <===============
===============> Day: 2 <===============
===============> Day: 3 <===============
===============> Day: 4 <===============
===============> Day: 5 <===============

In [21]:
# recommenders["popular_1_exp_0_seed_None"].connected_consumers[0]
conumers_ids = list(
    recommenders["popular_1_exp_0_seed_None"].connected_consumers.keys()
)
for i in conumers_ids:
    consumer_type = "niche" if i in niche_consumers_set else "general"
    print(
        f"{consumer_type} Consumer ID:",
        recommenders["popular_1_exp_0_seed_None"].connected_consumers[i].consumer_id,
    )
    print(
        "Documents Clicked:",
        len(recommenders["popular_1_exp_0_seed_None"].consumer_docs_ids_clicked[i]),
    )
    print()

general Consumer ID: 229
Documents Clicked: 1402

general Consumer ID: 109
Documents Clicked: 351

general Consumer ID: 406
Documents Clicked: 182

general Consumer ID: 450
Documents Clicked: 1043

niche Consumer ID: 49
Documents Clicked: 6

niche Consumer ID: 17
Documents Clicked: 5

niche Consumer ID: 23
Documents Clicked: 8

general Consumer ID: 383
Documents Clicked: 709

general Consumer ID: 387
Documents Clicked: 719

general Consumer ID: 228
Documents Clicked: 693

general Consumer ID: 556
Documents Clicked: 697

general Consumer ID: 265
Documents Clicked: 343

general Consumer ID: 69
Documents Clicked: 220

general Consumer ID: 354
Documents Clicked: 179

general Consumer ID: 380
Documents Clicked: 1021

general Consumer ID: 397
Documents Clicked: 348

general Consumer ID: 579
Documents Clicked: 1090

general Consumer ID: 451
Documents Clicked: 346

general Consumer ID: 259
Documents Clicked: 680

general Consumer ID: 470
Documents Clicked: 174

general Consumer ID: 478
Documents Clicked: 485

niche Consumer ID: 11
Documents Clicked: 6

general Consumer ID: 106
Documents Clicked: 1531

general Consumer ID: 213
Documents Clicked: 532

general Consumer ID: 421
Documents Clicked: 466

general Consumer ID: 334
Documents Clicked: 824

general Consumer ID: 452
Documents Clicked: 134

general Consumer ID: 585
Documents Clicked: 344

general Consumer ID: 93
Documents Clicked: 893

general Consumer ID: 575
Documents Clicked: 276

general Consumer ID: 340
Documents Clicked: 310

general Consumer ID: 216
Documents Clicked: 799

general Consumer ID: 112
Documents Clicked: 183

general Consumer ID: 417
Documents Clicked: 133

general Consumer ID: 360
Documents Clicked: 276

general Consumer ID: 215
Documents Clicked: 483

general Consumer ID: 72
Documents Clicked: 1100

general Consumer ID: 78
Documents Clicked: 697

niche Consumer ID: 59
Documents Clicked: 10

general Consumer ID: 214
Documents Clicked: 1041

general Consumer ID: 299
Documents Clicked: 165

general Consumer ID: 364
Documents Clicked: 174

general Consumer ID: 505
Documents Clicked: 1030

general Consumer ID: 318
Documents Clicked: 278

niche Consumer ID: 25
Documents Clicked: 7

general Consumer ID: 105
Documents Clicked: 343

niche Consumer ID: 39
Documents Clicked: 7

general Consumer ID: 179
Documents Clicked: 1119

general Consumer ID: 483
Documents Clicked: 468

general Consumer ID: 209
Documents Clicked: 275

general Consumer ID: 316
Documents Clicked: 1800

general Consumer ID: 362
Documents Clicked: 786

general Consumer ID: 187
Documents Clicked: 306

niche Consumer ID: 14
Documents Clicked: 10

general Consumer ID: 372
Documents Clicked: 1120

general Consumer ID: 487
Documents Clicked: 143

general Consumer ID: 86
Documents Clicked: 479

general Consumer ID: 464
Documents Clicked: 706

general Consumer ID: 590
Documents Clicked: 1002

general Consumer ID: 418
Documents Clicked: 482

niche Consumer ID: 9
Documents Clicked: 8

general Consumer ID: 554
Documents Clicked: 132

general Consumer ID: 489
Documents Clicked: 345

general Consumer ID: 248
Documents Clicked: 341

general Consumer ID: 386
Documents Clicked: 164

general Consumer ID: 427
Documents Clicked: 702

general Consumer ID: 219
Documents Clicked: 1299

general Consumer ID: 425
Documents Clicked: 697

general Consumer ID: 308
Documents Clicked: 891

general Consumer ID: 584
Documents Clicked: 174

general Consumer ID: 408
Documents Clicked: 788

general Consumer ID: 254
Documents Clicked: 220

general Consumer ID: 148
Documents Clicked: 175

general Consumer ID: 488
Documents Clicked: 798

general Consumer ID: 459
Documents Clicked: 868

general Consumer ID: 284
Documents Clicked: 663

general Consumer ID: 353
Documents Clicked: 162

niche Consumer ID: 42
Documents Clicked: 6

general Consumer ID: 98
Documents Clicked: 531

general Consumer ID: 68
Documents Clicked: 136

general Consumer ID: 330
Documents Clicked: 534

general Consumer ID: 591
Documents Clicked: 808

general Consumer ID: 223
Documents Clicked: 278

general Consumer ID: 513
Documents Clicked: 823

general Consumer ID: 525
Documents Clicked: 135

general Consumer ID: 162
Documents Clicked: 276

general Consumer ID: 436
Documents Clicked: 867

general Consumer ID: 405
Documents Clicked: 707

general Consumer ID: 479
Documents Clicked: 864

general Consumer ID: 180
Documents Clicked: 469

general Consumer ID: 530
Documents Clicked: 1099

general Consumer ID: 480
Documents Clicked: 137

general Consumer ID: 274
Documents Clicked: 276

general Consumer ID: 355
Documents Clicked: 341

general Consumer ID: 269
Documents Clicked: 1033

general Consumer ID: 90
Documents Clicked: 276

general Consumer ID: 296
Documents Clicked: 868

general Consumer ID: 352
Documents Clicked: 473

general Consumer ID: 297
Documents Clicked: 41

niche Consumer ID: 40
Documents Clicked: 8

general Consumer ID: 291
Documents Clicked: 342

general Consumer ID: 484
Documents Clicked: 1062

general Consumer ID: 242
Documents Clicked: 694

general Consumer ID: 127
Documents Clicked: 471

general Consumer ID: 424
Documents Clicked: 347

niche Consumer ID: 24
Documents Clicked: 6

general Consumer ID: 593
Documents Clicked: 616

general Consumer ID: 91
Documents Clicked: 702

general Consumer ID: 431
Documents Clicked: 429

general Consumer ID: 392
Documents Clicked: 136

general Consumer ID: 435
Documents Clicked: 676

general Consumer ID: 77
Documents Clicked: 346

general Consumer ID: 251
Documents Clicked: 161

general Consumer ID: 197
Documents Clicked: 665

general Consumer ID: 111
Documents Clicked: 345

general Consumer ID: 599
Documents Clicked: 346

general Consumer ID: 295
Documents Clicked: 342

general Consumer ID: 264
Documents Clicked: 164

general Consumer ID: 532
Documents Clicked: 277

general Consumer ID: 324
Documents Clicked: 1097

general Consumer ID: 142
Documents Clicked: 164

niche Consumer ID: 3
Documents Clicked: 5

general Consumer ID: 66
Documents Clicked: 344

niche Consumer ID: 27
Documents Clicked: 11

general Consumer ID: 282
Documents Clicked: 345

general Consumer ID: 518
Documents Clicked: 175

general Consumer ID: 415
Documents Clicked: 862

general Consumer ID: 311
Documents Clicked: 666

niche Consumer ID: 58
Documents Clicked: 6

general Consumer ID: 373
Documents Clicked: 1353

general Consumer ID: 173
Documents Clicked: 469

general Consumer ID: 403
Documents Clicked: 348

general Consumer ID: 234
Documents Clicked: 716

niche Consumer ID: 38
Documents Clicked: 7

niche Consumer ID: 26
Documents Clicked: 5

general Consumer ID: 398
Documents Clicked: 1046

general Consumer ID: 390
Documents Clicked: 273

niche Consumer ID: 7
Documents Clicked: 4

general Consumer ID: 482
Documents Clicked: 162

general Consumer ID: 453
Documents Clicked: 470

general Consumer ID: 361
Documents Clicked: 702

general Consumer ID: 578
Documents Clicked: 1085

general Consumer ID: 231
Documents Clicked: 864

general Consumer ID: 139
Documents Clicked: 696

general Consumer ID: 200
Documents Clicked: 342

general Consumer ID: 163
Documents Clicked: 702

general Consumer ID: 186
Documents Clicked: 346

general Consumer ID: 508
Documents Clicked: 273

general Consumer ID: 461
Documents Clicked: 1591

niche Consumer ID: 34
Documents Clicked: 5

general Consumer ID: 382
Documents Clicked: 163

general Consumer ID: 570
Documents Clicked: 480

general Consumer ID: 177
Documents Clicked: 164

general Consumer ID: 305
Documents Clicked: 136

general Consumer ID: 499
Documents Clicked: 693

niche Consumer ID: 6
Documents Clicked: 11

general Consumer ID: 249
Documents Clicked: 960

niche Consumer ID: 19
Documents Clicked: 3

general Consumer ID: 342
Documents Clicked: 344

general Consumer ID: 288
Documents Clicked: 859

niche Consumer ID: 30
Documents Clicked: 6

general Consumer ID: 194
Documents Clicked: 162

general Consumer ID: 100
Documents Clicked: 721

general Consumer ID: 241
Documents Clicked: 277

general Consumer ID: 395
Documents Clicked: 698

general Consumer ID: 543
Documents Clicked: 802

general Consumer ID: 394
Documents Clicked: 172

general Consumer ID: 266
Documents Clicked: 356

general Consumer ID: 136
Documents Clicked: 1768

general Consumer ID: 586
Documents Clicked: 702

general Consumer ID: 448
Documents Clicked: 705

general Consumer ID: 207
Documents Clicked: 892

general Consumer ID: 76
Documents Clicked: 39

general Consumer ID: 544
Documents Clicked: 346

general Consumer ID: 217
Documents Clicked: 342

general Consumer ID: 301
Documents Clicked: 348

general Consumer ID: 594
Documents Clicked: 163

general Consumer ID: 519
Documents Clicked: 166

general Consumer ID: 460
Documents Clicked: 720

general Consumer ID: 492
Documents Clicked: 211

general Consumer ID: 322
Documents Clicked: 137

general Consumer ID: 137
Documents Clicked: 343

general Consumer ID: 85
Documents Clicked: 344

general Consumer ID: 122
Documents Clicked: 706

general Consumer ID: 367
Documents Clicked: 341

general Consumer ID: 449
Documents Clicked: 343

general Consumer ID: 158
Documents Clicked: 471

general Consumer ID: 558
Documents Clicked: 273

general Consumer ID: 244
Documents Clicked: 347

general Consumer ID: 344
Documents Clicked: 1092

general Consumer ID: 104
Documents Clicked: 710

general Consumer ID: 568
Documents Clicked: 344

general Consumer ID: 545
Documents Clicked: 343

general Consumer ID: 485
Documents Clicked: 695

general Consumer ID: 79
Documents Clicked: 787

general Consumer ID: 366
Documents Clicked: 470

general Consumer ID: 533
Documents Clicked: 309

general Consumer ID: 551
Documents Clicked: 481

general Consumer ID: 312
Documents Clicked: 717

general Consumer ID: 81
Documents Clicked: 809

general Consumer ID: 540
Documents Clicked: 344

general Consumer ID: 384
Documents Clicked: 696

general Consumer ID: 588
Documents Clicked: 164

general Consumer ID: 474
Documents Clicked: 164

niche Consumer ID: 4
Documents Clicked: 7

general Consumer ID: 349
Documents Clicked: 133

general Consumer ID: 146
Documents Clicked: 1091

niche Consumer ID: 48
Documents Clicked: 3

general Consumer ID: 320
Documents Clicked: 337

general Consumer ID: 150
Documents Clicked: 473

general Consumer ID: 183
Documents Clicked: 872

general Consumer ID: 202
Documents Clicked: 698

general Consumer ID: 170
Documents Clicked: 344

general Consumer ID: 420
Documents Clicked: 163

general Consumer ID: 165
Documents Clicked: 345

general Consumer ID: 151
Documents Clicked: 276

general Consumer ID: 457
Documents Clicked: 468

general Consumer ID: 410
Documents Clicked: 479

general Consumer ID: 63
Documents Clicked: 137

general Consumer ID: 126
Documents Clicked: 698

general Consumer ID: 171
Documents Clicked: 342

general Consumer ID: 168
Documents Clicked: 693

general Consumer ID: 326
Documents Clicked: 137

general Consumer ID: 196
Documents Clicked: 163

general Consumer ID: 542
Documents Clicked: 705

general Consumer ID: 476
Documents Clicked: 1663

general Consumer ID: 506
Documents Clicked: 477

general Consumer ID: 310
Documents Clicked: 346

general Consumer ID: 332
Documents Clicked: 162

general Consumer ID: 210
Documents Clicked: 163

general Consumer ID: 389
Documents Clicked: 34

general Consumer ID: 129
Documents Clicked: 532

general Consumer ID: 71
Documents Clicked: 346

general Consumer ID: 138
Documents Clicked: 867

niche Consumer ID: 18
Documents Clicked: 7

niche Consumer ID: 22
Documents Clicked: 6

general Consumer ID: 445
Documents Clicked: 310

general Consumer ID: 152
Documents Clicked: 133

general Consumer ID: 281
Documents Clicked: 341

general Consumer ID: 113
Documents Clicked: 344

general Consumer ID: 327
Documents Clicked: 867

general Consumer ID: 566
Documents Clicked: 705

general Consumer ID: 271
Documents Clicked: 865

general Consumer ID: 429
Documents Clicked: 302

general Consumer ID: 471
Documents Clicked: 859

general Consumer ID: 134
Documents Clicked: 343

general Consumer ID: 521
Documents Clicked: 164

general Consumer ID: 257
Documents Clicked: 720

general Consumer ID: 595
Documents Clicked: 704

general Consumer ID: 576
Documents Clicked: 697

general Consumer ID: 240
Documents Clicked: 1410

general Consumer ID: 261
Documents Clicked: 790

general Consumer ID: 516
Documents Clicked: 698

general Consumer ID: 335
Documents Clicked: 474

general Consumer ID: 407
Documents Clicked: 167

general Consumer ID: 587
Documents Clicked: 664

niche Consumer ID: 16
Documents Clicked: 7

general Consumer ID: 331
Documents Clicked: 164

general Consumer ID: 555
Documents Clicked: 487

general Consumer ID: 339
Documents Clicked: 302

general Consumer ID: 527
Documents Clicked: 595

general Consumer ID: 468
Documents Clicked: 301

general Consumer ID: 211
Documents Clicked: 534

general Consumer ID: 434
Documents Clicked: 861

general Consumer ID: 496
Documents Clicked: 472

general Consumer ID: 447
Documents Clicked: 341

niche Consumer ID: 53
Documents Clicked: 5

general Consumer ID: 245
Documents Clicked: 221

general Consumer ID: 290
Documents Clicked: 343

general Consumer ID: 195
Documents Clicked: 1305

general Consumer ID: 227
Documents Clicked: 489

general Consumer ID: 260
Documents Clicked: 364

general Consumer ID: 573
Documents Clicked: 893

general Consumer ID: 400
Documents Clicked: 697

general Consumer ID: 531
Documents Clicked: 471

general Consumer ID: 65
Documents Clicked: 696

general Consumer ID: 270
Documents Clicked: 864

general Consumer ID: 232
Documents Clicked: 347

general Consumer ID: 235
Documents Clicked: 694

general Consumer ID: 333
Documents Clicked: 133

general Consumer ID: 426
Documents Clicked: 471

general Consumer ID: 224
Documents Clicked: 533

general Consumer ID: 130
Documents Clicked: 162

general Consumer ID: 371
Documents Clicked: 135

general Consumer ID: 184
Documents Clicked: 871

general Consumer ID: 279
Documents Clicked: 162

general Consumer ID: 523
Documents Clicked: 472

general Consumer ID: 94
Documents Clicked: 893

general Consumer ID: 348
Documents Clicked: 1098

general Consumer ID: 370
Documents Clicked: 164

general Consumer ID: 369
Documents Clicked: 341

general Consumer ID: 498
Documents Clicked: 276

general Consumer ID: 541
Documents Clicked: 718

general Consumer ID: 149
Documents Clicked: 676

general Consumer ID: 439
Documents Clicked: 807

general Consumer ID: 329
Documents Clicked: 865

general Consumer ID: 356
Documents Clicked: 136

general Consumer ID: 140
Documents Clicked: 698

general Consumer ID: 589
Documents Clicked: 166

general Consumer ID: 102
Documents Clicked: 699

general Consumer ID: 108
Documents Clicked: 342

general Consumer ID: 135
Documents Clicked: 275

general Consumer ID: 190
Documents Clicked: 477

general Consumer ID: 547
Documents Clicked: 499

general Consumer ID: 80
Documents Clicked: 863

general Consumer ID: 535
Documents Clicked: 705

general Consumer ID: 378
Documents Clicked: 126

niche Consumer ID: 1
Documents Clicked: 4

niche Consumer ID: 56
Documents Clicked: 3

general Consumer ID: 475
Documents Clicked: 183

general Consumer ID: 363
Documents Clicked: 705

general Consumer ID: 444
Documents Clicked: 471

general Consumer ID: 204
Documents Clicked: 342

general Consumer ID: 141
Documents Clicked: 315

general Consumer ID: 62
Documents Clicked: 293

general Consumer ID: 552
Documents Clicked: 466

general Consumer ID: 191
Documents Clicked: 480

general Consumer ID: 176
Documents Clicked: 136

general Consumer ID: 103
Documents Clicked: 472

general Consumer ID: 89
Documents Clicked: 135

general Consumer ID: 423
Documents Clicked: 703

general Consumer ID: 379
Documents Clicked: 714

general Consumer ID: 539
Documents Clicked: 165

general Consumer ID: 465
Documents Clicked: 895

general Consumer ID: 236
Documents Clicked: 131

general Consumer ID: 365
Documents Clicked: 698

general Consumer ID: 512
Documents Clicked: 219

general Consumer ID: 315
Documents Clicked: 1800

niche Consumer ID: 50
Documents Clicked: 8

niche Consumer ID: 55
Documents Clicked: 6

general Consumer ID: 220
Documents Clicked: 346

general Consumer ID: 302
Documents Clicked: 348

general Consumer ID: 193
Documents Clicked: 135

general Consumer ID: 188
Documents Clicked: 137

general Consumer ID: 583
Documents Clicked: 863

general Consumer ID: 167
Documents Clicked: 35

general Consumer ID: 309
Documents Clicked: 136

general Consumer ID: 493
Documents Clicked: 865

general Consumer ID: 553
Documents Clicked: 660

general Consumer ID: 99
Documents Clicked: 345

general Consumer ID: 247
Documents Clicked: 309

niche Consumer ID: 2
Documents Clicked: 12

general Consumer ID: 559
Documents Clicked: 470

general Consumer ID: 514
Documents Clicked: 344

general Consumer ID: 325
Documents Clicked: 691

general Consumer ID: 154
Documents Clicked: 163

general Consumer ID: 88
Documents Clicked: 477

general Consumer ID: 504
Documents Clicked: 343

general Consumer ID: 293
Documents Clicked: 347

general Consumer ID: 472
Documents Clicked: 890

general Consumer ID: 294
Documents Clicked: 488

general Consumer ID: 502
Documents Clicked: 486

general Consumer ID: 314
Documents Clicked: 136

niche Consumer ID: 43
Documents Clicked: 7

general Consumer ID: 119
Documents Clicked: 133

general Consumer ID: 110
Documents Clicked: 534

general Consumer ID: 563
Documents Clicked: 359

general Consumer ID: 409
Documents Clicked: 133

general Consumer ID: 172
Documents Clicked: 164

niche Consumer ID: 47
Documents Clicked: 3

general Consumer ID: 549
Documents Clicked: 1002

niche Consumer ID: 33
Documents Clicked: 8

general Consumer ID: 486
Documents Clicked: 210

general Consumer ID: 157
Documents Clicked: 274

general Consumer ID: 181
Documents Clicked: 347

general Consumer ID: 454
Documents Clicked: 36

general Consumer ID: 116
Documents Clicked: 1103

general Consumer ID: 222
Documents Clicked: 698

general Consumer ID: 253
Documents Clicked: 136

general Consumer ID: 238
Documents Clicked: 183

general Consumer ID: 118
Documents Clicked: 164

niche Consumer ID: 45
Documents Clicked: 8

general Consumer ID: 144
Documents Clicked: 790

general Consumer ID: 166
Documents Clicked: 134

general Consumer ID: 413
Documents Clicked: 711

general Consumer ID: 132
Documents Clicked: 698

general Consumer ID: 463
Documents Clicked: 889

niche Consumer ID: 31
Documents Clicked: 7

general Consumer ID: 430
Documents Clicked: 366

general Consumer ID: 351
Documents Clicked: 531

general Consumer ID: 440
Documents Clicked: 716

general Consumer ID: 128
Documents Clicked: 342

general Consumer ID: 490
Documents Clicked: 1065

general Consumer ID: 411
Documents Clicked: 468

general Consumer ID: 313
Documents Clicked: 665

general Consumer ID: 368
Documents Clicked: 343

general Consumer ID: 446
Documents Clicked: 792

general Consumer ID: 537
Documents Clicked: 346

general Consumer ID: 286
Documents Clicked: 661

general Consumer ID: 433
Documents Clicked: 341

general Consumer ID: 250
Documents Clicked: 1120

general Consumer ID: 221
Documents Clicked: 165

general Consumer ID: 280
Documents Clicked: 346

general Consumer ID: 199
Documents Clicked: 182

general Consumer ID: 561
Documents Clicked: 708

general Consumer ID: 87
Documents Clicked: 530

general Consumer ID: 456
Documents Clicked: 479

niche Consumer ID: 35
Documents Clicked: 5

niche Consumer ID: 36
Documents Clicked: 4

general Consumer ID: 307
Documents Clicked: 343

general Consumer ID: 567
Documents Clicked: 276

general Consumer ID: 131
Documents Clicked: 276

general Consumer ID: 133
Documents Clicked: 718

general Consumer ID: 262
Documents Clicked: 1118

general Consumer ID: 161
Documents Clicked: 134

general Consumer ID: 443
Documents Clicked: 345

general Consumer ID: 292
Documents Clicked: 173

niche Consumer ID: 57
Documents Clicked: 6

general Consumer ID: 550
Documents Clicked: 344

general Consumer ID: 357
Documents Clicked: 162

general Consumer ID: 272
Documents Clicked: 1201

general Consumer ID: 164
Documents Clicked: 616


In [22]:
len(movies_df[movies_df["genres"].str.contains("Western", case=False, na=False)])

167

In [23]:
len(niche_documents)
len(documents_df)

9724